// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: boulder_service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBoulderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoulderId string `protobuf:"bytes,1,opt,name=boulder_id,json=boulderId,proto3" json:"boulder_id,omitempty"`
}

func (x *GetBoulderRequest) Reset() {
	*x = GetBoulderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoulderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoulderRequest) ProtoMessage() {}

func (x *GetBoulderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoulderRequest.ProtoReflect.Descriptor instead.
func (*GetBoulderRequest) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetBoulderRequest) GetBoulderId() string {
	if x != nil {
		return x.BoulderId
	}
	return ""
}

type GetBoulderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boulder *Boulder `protobuf:"bytes,1,opt,name=boulder,proto3" json:"boulder,omitempty"`
}

func (x *GetBoulderResponse) Reset() {
	*x = GetBoulderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoulderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoulderResponse) ProtoMessage() {}

func (x *GetBoulderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoulderResponse.ProtoReflect.Descriptor instead.
func (*GetBoulderResponse) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoulderResponse) GetBoulder() *Boulder {
	if x != nil {
		return x.Boulder
	}
	return nil
}

type ListBouldersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchKey string `protobuf:"bytes,1,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
}

func (x *ListBouldersRequest) Reset() {
	*x = ListBouldersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBouldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBouldersRequest) ProtoMessage() {}

func (x *ListBouldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBouldersRequest.ProtoReflect.Descriptor instead.
func (*ListBouldersRequest) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListBouldersRequest) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

type ListBouldersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boulders []*Boulder `protobuf:"bytes,1,rep,name=boulders,proto3" json:"boulders,omitempty"`
}

func (x *ListBouldersResponse) Reset() {
	*x = ListBouldersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBouldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBouldersResponse) ProtoMessage() {}

func (x *ListBouldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBouldersResponse.ProtoReflect.Descriptor instead.
func (*ListBouldersResponse) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListBouldersResponse) GetBoulders() []*Boulder {
	if x != nil {
		return x.Boulders
	}
	return nil
}

type UpsertBoulderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boulder *Boulder `protobuf:"bytes,1,opt,name=boulder,proto3" json:"boulder,omitempty"`
}

func (x *UpsertBoulderRequest) Reset() {
	*x = UpsertBoulderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertBoulderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBoulderRequest) ProtoMessage() {}

func (x *UpsertBoulderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBoulderRequest.ProtoReflect.Descriptor instead.
func (*UpsertBoulderRequest) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertBoulderRequest) GetBoulder() *Boulder {
	if x != nil {
		return x.Boulder
	}
	return nil
}

type UpsertBoulderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpsertBoulderResponse) Reset() {
	*x = UpsertBoulderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertBoulderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBoulderResponse) ProtoMessage() {}

func (x *UpsertBoulderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBoulderResponse.ProtoReflect.Descriptor instead.
func (*UpsertBoulderResponse) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{5}
}

type UpsertApproachRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Approach *Approach `protobuf:"bytes,1,opt,name=approach,proto3" json:"approach,omitempty"`
	GpxXml   []byte    `protobuf:"bytes,2,opt,name=gpx_xml,json=gpxXml,proto3" json:"gpx_xml,omitempty"`
}

func (x *UpsertApproachRequest) Reset() {
	*x = UpsertApproachRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertApproachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertApproachRequest) ProtoMessage() {}

func (x *UpsertApproachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertApproachRequest.ProtoReflect.Descriptor instead.
func (*UpsertApproachRequest) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertApproachRequest) GetApproach() *Approach {
	if x != nil {
		return x.Approach
	}
	return nil
}

func (x *UpsertApproachRequest) GetGpxXml() []byte {
	if x != nil {
		return x.GpxXml
	}
	return nil
}

type UpsertApproachResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpsertApproachResponse) Reset() {
	*x = UpsertApproachResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertApproachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertApproachResponse) ProtoMessage() {}

func (x *UpsertApproachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertApproachResponse.ProtoReflect.Descriptor instead.
func (*UpsertApproachResponse) Descriptor() ([]byte, []int) {
	return file_boulder_service_proto_rawDescGZIP(), []int{7}
}

var File_boulder_service_proto protoreflect.FileDescriptor

var file_boulder_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0d, 0x62, 0x6f,
	0x75, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x3c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x75,
	0x6c, 0x64, 0x65, 0x72, 0x52, 0x07, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x34, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4b, 0x65, 0x79, 0x22, 0x40, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x62,
	0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x08, 0x62, 0x6f, 0x75,
	0x6c, 0x64, 0x65, 0x72, 0x73, 0x22, 0x3e, 0x0a, 0x14, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x42,
	0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x07, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x07, 0x62, 0x6f,
	0x75, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x42,
	0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5b,
	0x0a, 0x15, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x61, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x08, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x61,
	0x63, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x70, 0x78, 0x5f, 0x78, 0x6d, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x67, 0x70, 0x78, 0x58, 0x6d, 0x6c, 0x22, 0x18, 0x0a, 0x16, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xaf, 0x02, 0x0a, 0x16, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65,
	0x72, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x42, 0x6f,
	0x75, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x42, 0x6f, 0x75,
	0x6c, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0e,
	0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x12, 0x1a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x61, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x01, 0x2e, 0xba, 0x02, 0x03, 0x41,
	0x50, 0x49, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_boulder_service_proto_rawDescOnce sync.Once
	file_boulder_service_proto_rawDescData = file_boulder_service_proto_rawDesc
)

func file_boulder_service_proto_rawDescGZIP() []byte {
	file_boulder_service_proto_rawDescOnce.Do(func() {
		file_boulder_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_boulder_service_proto_rawDescData)
	})
	return file_boulder_service_proto_rawDescData
}

var file_boulder_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_boulder_service_proto_goTypes = []any{
	(*GetBoulderRequest)(nil),      // 0: api.GetBoulderRequest
	(*GetBoulderResponse)(nil),     // 1: api.GetBoulderResponse
	(*ListBouldersRequest)(nil),    // 2: api.ListBouldersRequest
	(*ListBouldersResponse)(nil),   // 3: api.ListBouldersResponse
	(*UpsertBoulderRequest)(nil),   // 4: api.UpsertBoulderRequest
	(*UpsertBoulderResponse)(nil),  // 5: api.UpsertBoulderResponse
	(*UpsertApproachRequest)(nil),  // 6: api.UpsertApproachRequest
	(*UpsertApproachResponse)(nil), // 7: api.UpsertApproachResponse
	(*Boulder)(nil),                // 8: api.Boulder
	(*Approach)(nil),               // 9: api.Approach
}
var file_boulder_service_proto_depIdxs = []int32{
	8, // 0: api.GetBoulderResponse.boulder:type_name -> api.Boulder
	8, // 1: api.ListBouldersResponse.boulders:type_name -> api.Boulder
	8, // 2: api.UpsertBoulderRequest.boulder:type_name -> api.Boulder
	9, // 3: api.UpsertApproachRequest.approach:type_name -> api.Approach
	0, // 4: api.BoulderApproachService.GetBoulder:input_type -> api.GetBoulderRequest
	2, // 5: api.BoulderApproachService.ListBoulders:input_type -> api.ListBouldersRequest
	4, // 6: api.BoulderApproachService.UpsertBoulder:input_type -> api.UpsertBoulderRequest
	6, // 7: api.BoulderApproachService.UpsertApproach:input_type -> api.UpsertApproachRequest
	1, // 8: api.BoulderApproachService.GetBoulder:output_type -> api.GetBoulderResponse
	3, // 9: api.BoulderApproachService.ListBoulders:output_type -> api.ListBouldersResponse
	5, // 10: api.BoulderApproachService.UpsertBoulder:output_type -> api.UpsertBoulderResponse
	7, // 11: api.BoulderApproachService.UpsertApproach:output_type -> api.UpsertApproachResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_boulder_service_proto_init() }
func file_boulder_service_proto_init() {
	if File_boulder_service_proto != nil {
		return
	}
	file_boulder_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_boulder_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetBoulderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetBoulderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListBouldersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListBouldersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertBoulderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertBoulderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertApproachRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpsertApproachResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_boulder_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boulder_service_proto_goTypes,
		DependencyIndexes: file_boulder_service_proto_depIdxs,
		MessageInfos:      file_boulder_service_proto_msgTypes,
	}.Build()
	File_boulder_service_proto = out.File
	file_boulder_service_proto_rawDesc = nil
	file_boulder_service_proto_goTypes = nil
	file_boulder_service_proto_depIdxs = nil
}
