// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: boulder.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Text      string  `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_boulder_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Point) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Approach struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApproachId  string   `protobuf:"bytes,1,opt,name=approach_id,json=approachId,proto3" json:"approach_id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Points      []*Point `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *Approach) Reset() {
	*x = Approach{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Approach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approach) ProtoMessage() {}

func (x *Approach) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approach.ProtoReflect.Descriptor instead.
func (*Approach) Descriptor() ([]byte, []int) {
	return file_boulder_proto_rawDescGZIP(), []int{1}
}

func (x *Approach) GetApproachId() string {
	if x != nil {
		return x.ApproachId
	}
	return ""
}

func (x *Approach) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Approach) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Approach) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Boulder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoulderId  string      `protobuf:"bytes,1,opt,name=boulder_id,json=boulderId,proto3" json:"boulder_id,omitempty"`
	Name       string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Approaches []*Approach `protobuf:"bytes,3,rep,name=approaches,proto3" json:"approaches,omitempty"`
}

func (x *Boulder) Reset() {
	*x = Boulder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_boulder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boulder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boulder) ProtoMessage() {}

func (x *Boulder) ProtoReflect() protoreflect.Message {
	mi := &file_boulder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boulder.ProtoReflect.Descriptor instead.
func (*Boulder) Descriptor() ([]byte, []int) {
	return file_boulder_proto_rawDescGZIP(), []int{2}
}

func (x *Boulder) GetBoulderId() string {
	if x != nil {
		return x.BoulderId
	}
	return ""
}

func (x *Boulder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Boulder) GetApproaches() []*Approach {
	if x != nil {
		return x.Approaches
	}
	return nil
}

var File_boulder_proto protoreflect.FileDescriptor

var file_boulder_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x55, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x08,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x61, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x22, 0x6b, 0x0a, 0x07, 0x42, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x75, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x61, 0x63, 0x68, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x65, 0x73,
	0x42, 0x16, 0x5a, 0x0e, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0xba, 0x02, 0x03, 0x41, 0x50, 0x49, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_boulder_proto_rawDescOnce sync.Once
	file_boulder_proto_rawDescData = file_boulder_proto_rawDesc
)

func file_boulder_proto_rawDescGZIP() []byte {
	file_boulder_proto_rawDescOnce.Do(func() {
		file_boulder_proto_rawDescData = protoimpl.X.CompressGZIP(file_boulder_proto_rawDescData)
	})
	return file_boulder_proto_rawDescData
}

var file_boulder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_boulder_proto_goTypes = []any{
	(*Point)(nil),    // 0: api.Point
	(*Approach)(nil), // 1: api.Approach
	(*Boulder)(nil),  // 2: api.Boulder
}
var file_boulder_proto_depIdxs = []int32{
	0, // 0: api.Approach.points:type_name -> api.Point
	1, // 1: api.Boulder.approaches:type_name -> api.Approach
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_boulder_proto_init() }
func file_boulder_proto_init() {
	if File_boulder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_boulder_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Approach); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_boulder_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Boulder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_boulder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_boulder_proto_goTypes,
		DependencyIndexes: file_boulder_proto_depIdxs,
		MessageInfos:      file_boulder_proto_msgTypes,
	}.Build()
	File_boulder_proto = out.File
	file_boulder_proto_rawDesc = nil
	file_boulder_proto_goTypes = nil
	file_boulder_proto_depIdxs = nil
}
