//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: boulder_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Api_BoulderApproachServiceClient`, then call methods of this protocol to make API calls.
internal protocol Api_BoulderApproachServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol? { get }

  func getBoulderRoutes(
    _ request: Api_GetBoulderRoutesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Api_GetBoulderRoutesRequest, Api_GetBoulderRoutesResponse>
}

extension Api_BoulderApproachServiceClientProtocol {
  internal var serviceName: String {
    return "api.BoulderApproachService"
  }

  /// Unary call to GetBoulderRoutes
  ///
  /// - Parameters:
  ///   - request: Request to send to GetBoulderRoutes.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getBoulderRoutes(
    _ request: Api_GetBoulderRoutesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Api_GetBoulderRoutesRequest, Api_GetBoulderRoutesResponse> {
    return self.makeUnaryCall(
      path: Api_BoulderApproachServiceClientMetadata.Methods.getBoulderRoutes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetBoulderRoutesInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Api_BoulderApproachServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Api_BoulderApproachServiceNIOClient")
internal final class Api_BoulderApproachServiceClient: Api_BoulderApproachServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the api.BoulderApproachService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Api_BoulderApproachServiceNIOClient: Api_BoulderApproachServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the api.BoulderApproachService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Api_BoulderApproachServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol? { get }

  func makeGetBoulderRoutesCall(
    _ request: Api_GetBoulderRoutesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Api_GetBoulderRoutesRequest, Api_GetBoulderRoutesResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_BoulderApproachServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Api_BoulderApproachServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetBoulderRoutesCall(
    _ request: Api_GetBoulderRoutesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Api_GetBoulderRoutesRequest, Api_GetBoulderRoutesResponse> {
    return self.makeAsyncUnaryCall(
      path: Api_BoulderApproachServiceClientMetadata.Methods.getBoulderRoutes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetBoulderRoutesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_BoulderApproachServiceAsyncClientProtocol {
  internal func getBoulderRoutes(
    _ request: Api_GetBoulderRoutesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Api_GetBoulderRoutesResponse {
    return try await self.performAsyncUnaryCall(
      path: Api_BoulderApproachServiceClientMetadata.Methods.getBoulderRoutes.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetBoulderRoutesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Api_BoulderApproachServiceAsyncClient: Api_BoulderApproachServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Api_BoulderApproachServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Api_BoulderApproachServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getBoulderRoutes'.
  func makeGetBoulderRoutesInterceptors() -> [ClientInterceptor<Api_GetBoulderRoutesRequest, Api_GetBoulderRoutesResponse>]
}

internal enum Api_BoulderApproachServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "BoulderApproachService",
    fullName: "api.BoulderApproachService",
    methods: [
      Api_BoulderApproachServiceClientMetadata.Methods.getBoulderRoutes,
    ]
  )

  internal enum Methods {
    internal static let getBoulderRoutes = GRPCMethodDescriptor(
      name: "GetBoulderRoutes",
      path: "/api.BoulderApproachService/GetBoulderRoutes",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Api_BoulderApproachServiceProvider: CallHandlerProvider {
  var interceptors: Api_BoulderApproachServiceServerInterceptorFactoryProtocol? { get }

  func getBoulderRoutes(request: Api_GetBoulderRoutesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Api_GetBoulderRoutesResponse>
}

extension Api_BoulderApproachServiceProvider {
  internal var serviceName: Substring {
    return Api_BoulderApproachServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetBoulderRoutes":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Api_GetBoulderRoutesRequest>(),
        responseSerializer: ProtobufSerializer<Api_GetBoulderRoutesResponse>(),
        interceptors: self.interceptors?.makeGetBoulderRoutesInterceptors() ?? [],
        userFunction: self.getBoulderRoutes(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Api_BoulderApproachServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Api_BoulderApproachServiceServerInterceptorFactoryProtocol? { get }

  func getBoulderRoutes(
    request: Api_GetBoulderRoutesRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Api_GetBoulderRoutesResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Api_BoulderApproachServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Api_BoulderApproachServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Api_BoulderApproachServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Api_BoulderApproachServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetBoulderRoutes":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Api_GetBoulderRoutesRequest>(),
        responseSerializer: ProtobufSerializer<Api_GetBoulderRoutesResponse>(),
        interceptors: self.interceptors?.makeGetBoulderRoutesInterceptors() ?? [],
        wrapping: { try await self.getBoulderRoutes(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Api_BoulderApproachServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getBoulderRoutes'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetBoulderRoutesInterceptors() -> [ServerInterceptor<Api_GetBoulderRoutesRequest, Api_GetBoulderRoutesResponse>]
}

internal enum Api_BoulderApproachServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "BoulderApproachService",
    fullName: "api.BoulderApproachService",
    methods: [
      Api_BoulderApproachServiceServerMetadata.Methods.getBoulderRoutes,
    ]
  )

  internal enum Methods {
    internal static let getBoulderRoutes = GRPCMethodDescriptor(
      name: "GetBoulderRoutes",
      path: "/api.BoulderApproachService/GetBoulderRoutes",
      type: GRPCCallType.unary
    )
  }
}
