//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: boulder_service.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `APIBoulderApproachServiceClient`, then call methods of this protocol to make API calls.
internal protocol APIBoulderApproachServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol? { get }

  func getApproach(
    _ request: APIGetApproachRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<APIGetApproachRequest, APIGetApproachResponse>

  func getBoulder(
    _ request: APIGetBoulderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<APIGetBoulderRequest, APIGetBoulderResponse>

  func listBoulders(
    _ request: APIListBouldersRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<APIListBouldersRequest, APIListBouldersResponse>

  func createBoulder(
    _ request: APICreateBoulderRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<APICreateBoulderRequest, APICreateBoulderResponse>

  func createApproach(
    _ request: APICreateApproachRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<APICreateApproachRequest, APICreateApproachResponse>
}

extension APIBoulderApproachServiceClientProtocol {
  internal var serviceName: String {
    return "api.BoulderApproachService"
  }

  /// Unary call to GetApproach
  ///
  /// - Parameters:
  ///   - request: Request to send to GetApproach.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getApproach(
    _ request: APIGetApproachRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<APIGetApproachRequest, APIGetApproachResponse> {
    return self.makeUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.getApproach.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetApproachInterceptors() ?? []
    )
  }

  /// Unary call to GetBoulder
  ///
  /// - Parameters:
  ///   - request: Request to send to GetBoulder.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getBoulder(
    _ request: APIGetBoulderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<APIGetBoulderRequest, APIGetBoulderResponse> {
    return self.makeUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.getBoulder.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetBoulderInterceptors() ?? []
    )
  }

  /// Unary call to ListBoulders
  ///
  /// - Parameters:
  ///   - request: Request to send to ListBoulders.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func listBoulders(
    _ request: APIListBouldersRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<APIListBouldersRequest, APIListBouldersResponse> {
    return self.makeUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.listBoulders.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListBouldersInterceptors() ?? []
    )
  }

  /// Unary call to CreateBoulder
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateBoulder.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createBoulder(
    _ request: APICreateBoulderRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<APICreateBoulderRequest, APICreateBoulderResponse> {
    return self.makeUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.createBoulder.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateBoulderInterceptors() ?? []
    )
  }

  /// Unary call to CreateApproach
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateApproach.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createApproach(
    _ request: APICreateApproachRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<APICreateApproachRequest, APICreateApproachResponse> {
    return self.makeUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.createApproach.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateApproachInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension APIBoulderApproachServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "APIBoulderApproachServiceNIOClient")
internal final class APIBoulderApproachServiceClient: APIBoulderApproachServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the api.BoulderApproachService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct APIBoulderApproachServiceNIOClient: APIBoulderApproachServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the api.BoulderApproachService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol APIBoulderApproachServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol? { get }

  func makeGetApproachCall(
    _ request: APIGetApproachRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<APIGetApproachRequest, APIGetApproachResponse>

  func makeGetBoulderCall(
    _ request: APIGetBoulderRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<APIGetBoulderRequest, APIGetBoulderResponse>

  func makeListBouldersCall(
    _ request: APIListBouldersRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<APIListBouldersRequest, APIListBouldersResponse>

  func makeCreateBoulderCall(
    _ request: APICreateBoulderRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<APICreateBoulderRequest, APICreateBoulderResponse>

  func makeCreateApproachCall(
    _ request: APICreateApproachRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<APICreateApproachRequest, APICreateApproachResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension APIBoulderApproachServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return APIBoulderApproachServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetApproachCall(
    _ request: APIGetApproachRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<APIGetApproachRequest, APIGetApproachResponse> {
    return self.makeAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.getApproach.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetApproachInterceptors() ?? []
    )
  }

  internal func makeGetBoulderCall(
    _ request: APIGetBoulderRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<APIGetBoulderRequest, APIGetBoulderResponse> {
    return self.makeAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.getBoulder.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetBoulderInterceptors() ?? []
    )
  }

  internal func makeListBouldersCall(
    _ request: APIListBouldersRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<APIListBouldersRequest, APIListBouldersResponse> {
    return self.makeAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.listBoulders.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListBouldersInterceptors() ?? []
    )
  }

  internal func makeCreateBoulderCall(
    _ request: APICreateBoulderRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<APICreateBoulderRequest, APICreateBoulderResponse> {
    return self.makeAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.createBoulder.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateBoulderInterceptors() ?? []
    )
  }

  internal func makeCreateApproachCall(
    _ request: APICreateApproachRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<APICreateApproachRequest, APICreateApproachResponse> {
    return self.makeAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.createApproach.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateApproachInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension APIBoulderApproachServiceAsyncClientProtocol {
  internal func getApproach(
    _ request: APIGetApproachRequest,
    callOptions: CallOptions? = nil
  ) async throws -> APIGetApproachResponse {
    return try await self.performAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.getApproach.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetApproachInterceptors() ?? []
    )
  }

  internal func getBoulder(
    _ request: APIGetBoulderRequest,
    callOptions: CallOptions? = nil
  ) async throws -> APIGetBoulderResponse {
    return try await self.performAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.getBoulder.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetBoulderInterceptors() ?? []
    )
  }

  internal func listBoulders(
    _ request: APIListBouldersRequest,
    callOptions: CallOptions? = nil
  ) async throws -> APIListBouldersResponse {
    return try await self.performAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.listBoulders.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListBouldersInterceptors() ?? []
    )
  }

  internal func createBoulder(
    _ request: APICreateBoulderRequest,
    callOptions: CallOptions? = nil
  ) async throws -> APICreateBoulderResponse {
    return try await self.performAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.createBoulder.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateBoulderInterceptors() ?? []
    )
  }

  internal func createApproach(
    _ request: APICreateApproachRequest,
    callOptions: CallOptions? = nil
  ) async throws -> APICreateApproachResponse {
    return try await self.performAsyncUnaryCall(
      path: APIBoulderApproachServiceClientMetadata.Methods.createApproach.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateApproachInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct APIBoulderApproachServiceAsyncClient: APIBoulderApproachServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: APIBoulderApproachServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol APIBoulderApproachServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'getApproach'.
  func makeGetApproachInterceptors() -> [ClientInterceptor<APIGetApproachRequest, APIGetApproachResponse>]

  /// - Returns: Interceptors to use when invoking 'getBoulder'.
  func makeGetBoulderInterceptors() -> [ClientInterceptor<APIGetBoulderRequest, APIGetBoulderResponse>]

  /// - Returns: Interceptors to use when invoking 'listBoulders'.
  func makeListBouldersInterceptors() -> [ClientInterceptor<APIListBouldersRequest, APIListBouldersResponse>]

  /// - Returns: Interceptors to use when invoking 'createBoulder'.
  func makeCreateBoulderInterceptors() -> [ClientInterceptor<APICreateBoulderRequest, APICreateBoulderResponse>]

  /// - Returns: Interceptors to use when invoking 'createApproach'.
  func makeCreateApproachInterceptors() -> [ClientInterceptor<APICreateApproachRequest, APICreateApproachResponse>]
}

internal enum APIBoulderApproachServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "BoulderApproachService",
    fullName: "api.BoulderApproachService",
    methods: [
      APIBoulderApproachServiceClientMetadata.Methods.getApproach,
      APIBoulderApproachServiceClientMetadata.Methods.getBoulder,
      APIBoulderApproachServiceClientMetadata.Methods.listBoulders,
      APIBoulderApproachServiceClientMetadata.Methods.createBoulder,
      APIBoulderApproachServiceClientMetadata.Methods.createApproach,
    ]
  )

  internal enum Methods {
    internal static let getApproach = GRPCMethodDescriptor(
      name: "GetApproach",
      path: "/api.BoulderApproachService/GetApproach",
      type: GRPCCallType.unary
    )

    internal static let getBoulder = GRPCMethodDescriptor(
      name: "GetBoulder",
      path: "/api.BoulderApproachService/GetBoulder",
      type: GRPCCallType.unary
    )

    internal static let listBoulders = GRPCMethodDescriptor(
      name: "ListBoulders",
      path: "/api.BoulderApproachService/ListBoulders",
      type: GRPCCallType.unary
    )

    internal static let createBoulder = GRPCMethodDescriptor(
      name: "CreateBoulder",
      path: "/api.BoulderApproachService/CreateBoulder",
      type: GRPCCallType.unary
    )

    internal static let createApproach = GRPCMethodDescriptor(
      name: "CreateApproach",
      path: "/api.BoulderApproachService/CreateApproach",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol APIBoulderApproachServiceProvider: CallHandlerProvider {
  var interceptors: APIBoulderApproachServiceServerInterceptorFactoryProtocol? { get }

  func getApproach(request: APIGetApproachRequest, context: StatusOnlyCallContext) -> EventLoopFuture<APIGetApproachResponse>

  func getBoulder(request: APIGetBoulderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<APIGetBoulderResponse>

  func listBoulders(request: APIListBouldersRequest, context: StatusOnlyCallContext) -> EventLoopFuture<APIListBouldersResponse>

  func createBoulder(request: APICreateBoulderRequest, context: StatusOnlyCallContext) -> EventLoopFuture<APICreateBoulderResponse>

  func createApproach(request: APICreateApproachRequest, context: StatusOnlyCallContext) -> EventLoopFuture<APICreateApproachResponse>
}

extension APIBoulderApproachServiceProvider {
  internal var serviceName: Substring {
    return APIBoulderApproachServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetApproach":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APIGetApproachRequest>(),
        responseSerializer: ProtobufSerializer<APIGetApproachResponse>(),
        interceptors: self.interceptors?.makeGetApproachInterceptors() ?? [],
        userFunction: self.getApproach(request:context:)
      )

    case "GetBoulder":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APIGetBoulderRequest>(),
        responseSerializer: ProtobufSerializer<APIGetBoulderResponse>(),
        interceptors: self.interceptors?.makeGetBoulderInterceptors() ?? [],
        userFunction: self.getBoulder(request:context:)
      )

    case "ListBoulders":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APIListBouldersRequest>(),
        responseSerializer: ProtobufSerializer<APIListBouldersResponse>(),
        interceptors: self.interceptors?.makeListBouldersInterceptors() ?? [],
        userFunction: self.listBoulders(request:context:)
      )

    case "CreateBoulder":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APICreateBoulderRequest>(),
        responseSerializer: ProtobufSerializer<APICreateBoulderResponse>(),
        interceptors: self.interceptors?.makeCreateBoulderInterceptors() ?? [],
        userFunction: self.createBoulder(request:context:)
      )

    case "CreateApproach":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APICreateApproachRequest>(),
        responseSerializer: ProtobufSerializer<APICreateApproachResponse>(),
        interceptors: self.interceptors?.makeCreateApproachInterceptors() ?? [],
        userFunction: self.createApproach(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol APIBoulderApproachServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: APIBoulderApproachServiceServerInterceptorFactoryProtocol? { get }

  func getApproach(
    request: APIGetApproachRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> APIGetApproachResponse

  func getBoulder(
    request: APIGetBoulderRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> APIGetBoulderResponse

  func listBoulders(
    request: APIListBouldersRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> APIListBouldersResponse

  func createBoulder(
    request: APICreateBoulderRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> APICreateBoulderResponse

  func createApproach(
    request: APICreateApproachRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> APICreateApproachResponse
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension APIBoulderApproachServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return APIBoulderApproachServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return APIBoulderApproachServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: APIBoulderApproachServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "GetApproach":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APIGetApproachRequest>(),
        responseSerializer: ProtobufSerializer<APIGetApproachResponse>(),
        interceptors: self.interceptors?.makeGetApproachInterceptors() ?? [],
        wrapping: { try await self.getApproach(request: $0, context: $1) }
      )

    case "GetBoulder":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APIGetBoulderRequest>(),
        responseSerializer: ProtobufSerializer<APIGetBoulderResponse>(),
        interceptors: self.interceptors?.makeGetBoulderInterceptors() ?? [],
        wrapping: { try await self.getBoulder(request: $0, context: $1) }
      )

    case "ListBoulders":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APIListBouldersRequest>(),
        responseSerializer: ProtobufSerializer<APIListBouldersResponse>(),
        interceptors: self.interceptors?.makeListBouldersInterceptors() ?? [],
        wrapping: { try await self.listBoulders(request: $0, context: $1) }
      )

    case "CreateBoulder":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APICreateBoulderRequest>(),
        responseSerializer: ProtobufSerializer<APICreateBoulderResponse>(),
        interceptors: self.interceptors?.makeCreateBoulderInterceptors() ?? [],
        wrapping: { try await self.createBoulder(request: $0, context: $1) }
      )

    case "CreateApproach":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<APICreateApproachRequest>(),
        responseSerializer: ProtobufSerializer<APICreateApproachResponse>(),
        interceptors: self.interceptors?.makeCreateApproachInterceptors() ?? [],
        wrapping: { try await self.createApproach(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol APIBoulderApproachServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'getApproach'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetApproachInterceptors() -> [ServerInterceptor<APIGetApproachRequest, APIGetApproachResponse>]

  /// - Returns: Interceptors to use when handling 'getBoulder'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetBoulderInterceptors() -> [ServerInterceptor<APIGetBoulderRequest, APIGetBoulderResponse>]

  /// - Returns: Interceptors to use when handling 'listBoulders'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListBouldersInterceptors() -> [ServerInterceptor<APIListBouldersRequest, APIListBouldersResponse>]

  /// - Returns: Interceptors to use when handling 'createBoulder'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateBoulderInterceptors() -> [ServerInterceptor<APICreateBoulderRequest, APICreateBoulderResponse>]

  /// - Returns: Interceptors to use when handling 'createApproach'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateApproachInterceptors() -> [ServerInterceptor<APICreateApproachRequest, APICreateApproachResponse>]
}

internal enum APIBoulderApproachServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "BoulderApproachService",
    fullName: "api.BoulderApproachService",
    methods: [
      APIBoulderApproachServiceServerMetadata.Methods.getApproach,
      APIBoulderApproachServiceServerMetadata.Methods.getBoulder,
      APIBoulderApproachServiceServerMetadata.Methods.listBoulders,
      APIBoulderApproachServiceServerMetadata.Methods.createBoulder,
      APIBoulderApproachServiceServerMetadata.Methods.createApproach,
    ]
  )

  internal enum Methods {
    internal static let getApproach = GRPCMethodDescriptor(
      name: "GetApproach",
      path: "/api.BoulderApproachService/GetApproach",
      type: GRPCCallType.unary
    )

    internal static let getBoulder = GRPCMethodDescriptor(
      name: "GetBoulder",
      path: "/api.BoulderApproachService/GetBoulder",
      type: GRPCCallType.unary
    )

    internal static let listBoulders = GRPCMethodDescriptor(
      name: "ListBoulders",
      path: "/api.BoulderApproachService/ListBoulders",
      type: GRPCCallType.unary
    )

    internal static let createBoulder = GRPCMethodDescriptor(
      name: "CreateBoulder",
      path: "/api.BoulderApproachService/CreateBoulder",
      type: GRPCCallType.unary
    )

    internal static let createApproach = GRPCMethodDescriptor(
      name: "CreateApproach",
      path: "/api.BoulderApproachService/CreateApproach",
      type: GRPCCallType.unary
    )
  }
}
